language: python
before_install:
    - "pip3 install --only-binary=scipy,numpy,pandas numpy scipy pandas"
python:
    - "3.5"
    - "3.6"
install: "pip3 install --prefix=~/.local ."
script: ./setup.py test
